# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setBaseSize(QtCore.QSize(799, 600))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Download = QtWidgets.QWidget()
        self.Download.setObjectName("Download")
        self.labelsymbol = QtWidgets.QLabel(self.Download)
        self.labelsymbol.setGeometry(QtCore.QRect(207, 6, 40, 19))
        self.labelsymbol.setText("")
        self.labelsymbol.setObjectName("labelsymbol")
        self.layoutWidget = QtWidgets.QWidget(self.Download)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 10, 341, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButtonDaily = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonDaily.sizePolicy().hasHeightForWidth())
        self.radioButtonDaily.setSizePolicy(sizePolicy)
        self.radioButtonDaily.setMinimumSize(QtCore.QSize(80, 20))
        self.radioButtonDaily.setBaseSize(QtCore.QSize(80, 20))
        self.radioButtonDaily.setObjectName("radioButtonDaily")
        self.buttonGroupWeeklyDaily = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroupWeeklyDaily.setObjectName("buttonGroupWeeklyDaily")
        self.buttonGroupWeeklyDaily.addButton(self.radioButtonDaily)
        self.gridLayout.addWidget(self.radioButtonDaily, 1, 0, 1, 1)
        self.radioButtonWeekly = QtWidgets.QRadioButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonWeekly.sizePolicy().hasHeightForWidth())
        self.radioButtonWeekly.setSizePolicy(sizePolicy)
        self.radioButtonWeekly.setMinimumSize(QtCore.QSize(80, 20))
        self.radioButtonWeekly.setBaseSize(QtCore.QSize(80, 20))
        self.radioButtonWeekly.setObjectName("radioButtonWeekly")
        self.buttonGroupWeeklyDaily.addButton(self.radioButtonWeekly)
        self.gridLayout.addWidget(self.radioButtonWeekly, 0, 0, 1, 1)
        self.dateEditStart = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEditStart.setMinimumSize(QtCore.QSize(120, 40))
        self.dateEditStart.setBaseSize(QtCore.QSize(120, 40))
        self.dateEditStart.setStyleSheet("\n"
"QDateEdit{ color: red,basesize:120x48 }\n"
"")
        self.dateEditStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditStart.setMaximumDate(QtCore.QDate(2019, 1, 1))
        self.dateEditStart.setMinimumDate(QtCore.QDate(1986, 1, 1))
        self.dateEditStart.setCalendarPopup(True)
        self.dateEditStart.setObjectName("dateEditStart")
        self.gridLayout.addWidget(self.dateEditStart, 0, 2, 2, 1)
        self.labelStartDate = QtWidgets.QLabel(self.layoutWidget)
        self.labelStartDate.setObjectName("labelStartDate")
        self.gridLayout.addWidget(self.labelStartDate, 0, 1, 2, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.Download)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 100, 331, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelDatebaseName = QtWidgets.QLabel(self.layoutWidget1)
        self.labelDatebaseName.setMinimumSize(QtCore.QSize(120, 40))
        self.labelDatebaseName.setBaseSize(QtCore.QSize(120, 40))
        self.labelDatebaseName.setObjectName("labelDatebaseName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelDatebaseName)
        self.lineEditDB = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDB.sizePolicy().hasHeightForWidth())
        self.lineEditDB.setSizePolicy(sizePolicy)
        self.lineEditDB.setMinimumSize(QtCore.QSize(120, 40))
        self.lineEditDB.setBaseSize(QtCore.QSize(120, 40))
        self.lineEditDB.setObjectName("lineEditDB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditDB)
        self.layoutWidget2 = QtWidgets.QWidget(self.Download)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 160, 246, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_2.setMinimumSize(QtCore.QSize(120, 40))
        self.radioButton_2.setBaseSize(QtCore.QSize(120, 40))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroupNewUpdate = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroupNewUpdate.setObjectName("buttonGroupNewUpdate")
        self.buttonGroupNewUpdate.addButton(self.radioButton_2)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton.setMinimumSize(QtCore.QSize(120, 40))
        self.radioButton.setBaseSize(QtCore.QSize(120, 40))
        self.radioButton.setObjectName("radioButton")
        self.buttonGroupNewUpdate.addButton(self.radioButton)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton)
        self.layoutWidget3 = QtWidgets.QWidget(self.Download)
        self.layoutWidget3.setGeometry(QtCore.QRect(250, 230, 246, 50))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.pushButtonStop = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButtonStop.setEnabled(False)
        self.pushButtonStop.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonStop.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButtonStop)
        self.pushButtonTickers = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButtonTickers.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButtonTickers.setBaseSize(QtCore.QSize(120, 48))
        self.pushButtonTickers.setObjectName("pushButtonTickers")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonTickers)
        self.widget = QtWidgets.QWidget(self.Download)
        self.widget.setGeometry(QtCore.QRect(360, 20, 311, 42))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelEndDate = QtWidgets.QLabel(self.widget)
        self.labelEndDate.setObjectName("labelEndDate")
        self.gridLayout_2.addWidget(self.labelEndDate, 0, 0, 1, 1)
        self.dateEditEnd = QtWidgets.QDateEdit(self.widget)
        self.dateEditEnd.setMinimumSize(QtCore.QSize(120, 40))
        self.dateEditEnd.setBaseSize(QtCore.QSize(120, 40))
        self.dateEditEnd.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 3, 14), QtCore.QTime(23, 59, 59)))
        self.dateEditEnd.setMaximumDate(QtCore.QDate(2022, 1, 1))
        self.dateEditEnd.setMinimumDate(QtCore.QDate(1986, 1, 1))
        self.dateEditEnd.setCalendarPopup(True)
        self.dateEditEnd.setObjectName("dateEditEnd")
        self.gridLayout_2.addWidget(self.dateEditEnd, 0, 1, 1, 1)
        self.checkBoxToday = QtWidgets.QCheckBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxToday.sizePolicy().hasHeightForWidth())
        self.checkBoxToday.setSizePolicy(sizePolicy)
        self.checkBoxToday.setMinimumSize(QtCore.QSize(44, 16))
        self.checkBoxToday.setBaseSize(QtCore.QSize(44, 16))
        self.checkBoxToday.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.checkBoxToday.setAutoFillBackground(True)
        self.checkBoxToday.setStyleSheet("{baseSize: 44x16}")
        self.checkBoxToday.setObjectName("checkBoxToday")
        self.gridLayout_2.addWidget(self.checkBoxToday, 0, 2, 1, 1)
        self.tabWidget.addTab(self.Download, "")
        self.tabDescribe = QtWidgets.QWidget()
        self.tabDescribe.setObjectName("tabDescribe")
        self.tabWidget.addTab(self.tabDescribe, "")
        self.Indicators = QtWidgets.QWidget()
        self.Indicators.setObjectName("Indicators")
        self.tabWidget.addTab(self.Indicators, "")
        self.Algo = QtWidgets.QWidget()
        self.Algo.setObjectName("Algo")
        self.tabWidget.addTab(self.Algo, "")
        self.tabbyStock = QtWidgets.QWidget()
        self.tabbyStock.setObjectName("tabbyStock")
        self.tabWidget.addTab(self.tabbyStock, "")
        self.Apply = QtWidgets.QWidget()
        self.Apply.setObjectName("Apply")
        self.tabWidget.addTab(self.Apply, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButtonTickers.clicked.connect(MainWindow.getallsymbols)
        self.pushButtonStop.clicked.connect(MainWindow.stopdailydownload)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonTickers, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButtonDaily.setText(_translate("MainWindow", "Daily"))
        self.radioButtonWeekly.setText(_translate("MainWindow", "Weekly"))
        self.labelStartDate.setText(_translate("MainWindow", "Start Date"))
        self.labelDatebaseName.setText(_translate("MainWindow", "Database Name"))
        self.radioButton_2.setText(_translate("MainWindow", "Update"))
        self.radioButton.setText(_translate("MainWindow", "New "))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        self.pushButtonTickers.setText(_translate("MainWindow", "Get Data"))
        self.labelEndDate.setText(_translate("MainWindow", "End Date"))
        self.checkBoxToday.setText(_translate("MainWindow", "Today"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Download), _translate("MainWindow", "Download"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDescribe), _translate("MainWindow", "Describe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Indicators), _translate("MainWindow", "Indicators"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Algo), _translate("MainWindow", "Algo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabbyStock), _translate("MainWindow", "byStock"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Apply), _translate("MainWindow", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

